### ISSUE TITLE
default permissions are not working with this package

### ISSUE THREAD

**Issue by crocofied** [Dorukyum/pycord-multicog#5]
When I try to use the default_permissions decorator with this package, these permissions are just ignored.

**Comment by Dorukyum** [comment]
You can't set default permissions for subcommands, this is a Discord limitation.

**Comment by crocofied** [comment]
Can I set them for the entire Slash Command Group?

**Comment by Dorukyum** [comment]
> Can I set them for the entire Slash Command Group?

Yes, refer to the Pycord documentation.
